import { useEffect, useState } from 'react'
import { automationApi } from '../api/automationApi'
import { ApiError } from '../api/client'
import { EmptyState, ErrorNotice, LoadingState, PageHeader, Panel, StatusBadge } from '../components/ui'
import { formatDate, formatDuration, statusTone } from '../lib/format'
import type { AutomationConfig, AutomationExecution, AutomationRun, Page } from '../types'
import type { ProjectPageProps } from './pageTypes'

const defaultConfig=(projectId:string):AutomationConfig=>({projectId,enabled:false,progressSummaryEnabled:true,activitySummaryEnabled:true,errorWatchEnabled:true,environmentWatchEnabled:true,intervalSeconds:300,lastRunAt:null,nextRunAt:null,createdAt:'',updatedAt:'',version:0})

export default function AutomationPage({projectId,project,refreshOverview}:ProjectPageProps){
  const[config,setConfig]=useState<AutomationConfig|null>(null);const[runs,setRuns]=useState<Page<AutomationRun>|null>(null);const[lastRun,setLastRun]=useState<AutomationExecution|null>(null);const[loading,setLoading]=useState(false);const[error,setError]=useState<string|null>(null);const[notice,setNotice]=useState<string|null>(null)
  const load=async()=>{if(!projectId)return;setError(null);const [configResult,runsResult]=await Promise.allSettled([automationApi.get(projectId),automationApi.runs(projectId)]);setConfig(configResult.status==='fulfilled'?configResult.value:defaultConfig(projectId));if(runsResult.status==='fulfilled')setRuns(runsResult.value)}
  useEffect(()=>{setConfig(null);setRuns(null);setLastRun(null);if(projectId)void load()},[projectId])
  if(!projectId)return <EmptyState title="Project가 필요합니다" description="Automation 설정과 실행 이력은 Project별로 저장됩니다."/>
  if(!config)return <LoadingState label="Automation 설정 확인 중"/>
  const update=(key:keyof AutomationConfig,value:boolean|number)=>setConfig({...config,[key]:value})
  const save=async()=>{setLoading(true);setError(null);setNotice(null);try{const {lastRunAt:_,nextRunAt:__,createdAt:___,updatedAt:____,version:_____,...request}=config;setConfig(await automationApi.save(request));setNotice('Automation 설정을 저장했습니다.')}catch(reason){setError(reason instanceof ApiError?reason.message:'설정 저장에 실패했습니다.')}finally{setLoading(false)}}
  const run=async()=>{setLoading(true);setError(null);setNotice(null);try{const result=await automationApi.run(projectId);setLastRun(result);setNotice(result.status==='NO_CHANGE'?'변경 없음 · LLM 호출을 생략했습니다.':`실행 완료 · ${result.status}`);await load();await refreshOverview()}catch(reason){setError(reason instanceof ApiError?reason.message:'수동 실행에 실패했습니다.')}finally{setLoading(false)}}
  return <><PageHeader eyebrow="자동화" title="프로젝트 정기 확인" description={`${project?.name??projectId}의 읽기 전용 Workflow를 변경이 있을 때만 실행합니다.`} action={<div className="button-row"><button className="button button-secondary" onClick={save} disabled={loading}>저장</button><button className="button button-primary" onClick={run} disabled={loading}>지금 실행</button></div>}/>{error&&<ErrorNotice message={error}/>} {notice&&<div className="notice notice-success">{notice}</div>} {loading&&<LoadingState label="Automation 실행 중"/>}
    <div className="automation-grid"><Panel><div className="panel-heading"><div><span className="eyebrow">CONFIGURATION</span><h2>Project automation</h2></div><StatusBadge label={config.enabled?'ENABLED':'DISABLED'} tone={config.enabled?'ok':'muted'}/></div><div className="toggle-list"><Toggle label="Automation enabled" description="Scheduler가 이 Project를 실행합니다." checked={config.enabled} onChange={value=>update('enabled',value)}/><Toggle label="Progress Summary" description="변경 시 진행 상태를 분석합니다." checked={config.progressSummaryEnabled} onChange={value=>update('progressSummaryEnabled',value)}/><Toggle label="Activity Summary" description="변경 시 최근 작업을 요약합니다." checked={config.activitySummaryEnabled} onChange={value=>update('activitySummaryEnabled',value)}/><Toggle label="Error Watch" description="새 오류와 유사 사례를 확인합니다." checked={config.errorWatchEnabled} onChange={value=>update('errorWatchEnabled',value)}/><Toggle label="Environment Watch" description="Docker, DB, Ollama 상태를 확인합니다." checked={config.environmentWatchEnabled} onChange={value=>update('environmentWatchEnabled',value)}/></div><label className="interval-field">실행 간격 <div><input aria-label="실행 간격" type="number" min={60} max={604800} value={config.intervalSeconds} onChange={event=>update('intervalSeconds',Math.max(60,Math.min(604800,Number(event.target.value))))}/><span>seconds</span></div><small>60초 이상 · 최대 7일</small></label></Panel>
      <Panel><div className="panel-heading"><div><span className="eyebrow">최근 결과</span><h2>수동 실행</h2></div>{lastRun&&<StatusBadge label={lastRun.status} tone={statusTone(lastRun.status)}/>}</div>{lastRun?<dl className="detail-list"><div><dt>Change detected</dt><dd>{lastRun.changeDetected?'Yes':'No'}</dd></div><div><dt>LLM invoked</dt><dd>{lastRun.llmInvoked?'Yes':'Skipped'}</dd></div><div><dt>Duration</dt><dd>{formatDuration(lastRun.totalDurationMillis)}</dd></div><div><dt>Notifications</dt><dd>{lastRun.notifications.length}</dd></div></dl>:<div className="inline-empty">Run Now 결과가 여기에 표시됩니다.</div>}</Panel></div>
    <Panel><div className="panel-heading"><div><span className="eyebrow">실행 이력</span><h2>최근 실행</h2></div><span>{runs?.totalElements??0} runs</span></div><div className="table-wrap"><table><thead><tr><th>Status</th><th>Trigger</th><th>Started</th><th>Change</th><th>Duration</th><th>Summary</th></tr></thead><tbody>{runs?.content.map(run=><tr key={run.id}><td><StatusBadge label={run.status} tone={statusTone(run.status)}/></td><td>{run.triggerType}</td><td>{formatDate(run.startedAt)}</td><td>{run.changeDetected?'Detected':'No change'}</td><td>{formatDuration(run.durationMillis)}</td><td>{run.summary??run.errorMessage??'—'}</td></tr>)}</tbody></table>{!runs?.content.length&&<div className="inline-empty">아직 실행 이력이 없습니다.</div>}</div></Panel>
  </>
}

function Toggle({label,description,checked,onChange}:{label:string;description:string;checked:boolean;onChange:(value:boolean)=>void}){return <label className="toggle-row"><div><strong>{label}</strong><span>{description}</span></div><input type="checkbox" checked={checked} onChange={event=>onChange(event.target.checked)}/><i/></label>}
