import { PageHeader, Panel, StatusBadge } from '../components/ui'
import { statusTone } from '../lib/format'
import type { WorkspaceDiscovery } from '../types'
import type { ProjectPageProps } from './pageTypes'

export default function SettingsPage({project,overview,discovery,backendError}:{discovery:WorkspaceDiscovery|null;backendError:string|null}&ProjectPageProps){
  const services=[['Backend',backendError?'UNAVAILABLE':'AVAILABLE'],['Docker',overview?.docker?.status??'UNKNOWN'],['Ollama',overview?.ollama?.status??'UNKNOWN'],['PostgreSQL',overview?.database?.status??'UNKNOWN'],['pgvector',overview?.database?.pgvectorAvailable===true?'AVAILABLE':'UNKNOWN']]
  return <><PageHeader eyebrow="SETTINGS" title="Local environment" description="민감한 연결 정보 없이 현재 LocalRAG 실행 상태를 확인합니다."/><div className="settings-grid"><Panel><div className="panel-heading"><div><span className="eyebrow">RUNTIME</span><h2>Service status</h2></div></div><div className="service-list">{services.map(([name,status])=><div key={String(name)}><span>{String(name)}</span><StatusBadge label={String(status)} tone={statusTone(String(status))}/></div>)}</div><div className="notice notice-info"><strong>서비스가 꺼져 있나요?</strong><span>PostgreSQL, Ollama, Backend 순서로 실행한 뒤 이 화면에서 연결 상태를 다시 확인하세요.</span></div></Panel><Panel><div className="panel-heading"><div><span className="eyebrow">MODELS</span><h2>Local AI baseline</h2></div></div><dl className="detail-list"><div><dt>Chat model</dt><dd>qwen3:8b</dd></div><div><dt>Embedding model</dt><dd>{overview?.index?.embeddingModel??'qwen3-embedding:0.6b'}</dd></div><div><dt>Dimensions</dt><dd>{overview?.index?.dimensions??1024}</dd></div><div><dt>Provider</dt><dd>Ollama · local only</dd></div></dl></Panel><Panel className="panel-wide"><div className="panel-heading"><div><span className="eyebrow">SCOPE</span><h2>Workspace boundary</h2></div></div><dl className="detail-list"><div><dt>Workspace</dt><dd>{discovery?.workspaceRoot?.split(/[\\/]/).filter(Boolean).at(-1)??'—'}</dd></div><div><dt>Selected Project</dt><dd>{project?.projectId??'선택되지 않음'}</dd></div><div><dt>Discovered Projects</dt><dd>{discovery?.projects.length??0}</dd></div><div><dt>Containers</dt><dd>{discovery?.containers.length??0}</dd></div></dl><p className="muted">절대 경로 입력이나 Workspace 밖 파일 접근 기능은 UI에 제공하지 않습니다.</p></Panel></div></>
}
