import { PageHeader, Panel, StatusBadge } from '../components/ui'
import { statusTone } from '../lib/format'
import type { WorkspaceDiscovery } from '../types'
import type { ProjectPageProps } from './pageTypes'
import type { BackendReadiness } from '../api/client'

export default function SettingsPage({project,overview,discovery,backendError,backendStatus,retryStartup}:{discovery:WorkspaceDiscovery|null;backendError:string|null;backendStatus:BackendReadiness;retryStartup:()=>void}&ProjectPageProps){
  const services=[['Backend',backendError?'UNAVAILABLE':backendStatus],['Docker',overview?.docker?.status??'UNKNOWN'],['Ollama',overview?.ollama?.status??'UNKNOWN'],['PostgreSQL',overview?.database?.status??'UNKNOWN'],['pgvector',overview?.database?.pgvectorAvailable===true?'AVAILABLE':'UNKNOWN']]
  return <><PageHeader eyebrow="설정" title="로컬 실행 환경" description="민감한 연결 정보 없이 현재 LocalRAG 실행 상태를 확인합니다."/><div className="settings-grid"><Panel><div className="panel-heading"><div><span className="eyebrow">서비스</span><h2>서비스 상태</h2></div></div><div className="service-list">{services.map(([name,status])=><div key={String(name)}><span>{String(name)}</span><StatusBadge label={String(status)} tone={statusTone(String(status))}/></div>)}</div><div className="notice notice-info"><strong>실행 문제가 있나요?</strong><span>서비스 상태를 다시 확인하고 필요한 Runtime을 준비합니다.</span><button className="button button-secondary" onClick={retryStartup}>다시 준비</button></div></Panel><Panel><div className="panel-heading"><div><span className="eyebrow">모델</span><h2>로컬 AI 설정</h2></div></div><dl className="detail-list"><div><dt>채팅 모델</dt><dd>qwen3:8b</dd></div><div><dt>임베딩 모델</dt><dd>{overview?.index?.embeddingModel??'qwen3-embedding:0.6b'}</dd></div><div><dt>벡터 차원 (기본 모델)</dt><dd>{overview?.index?.dimensions||1024}</dd></div><div><dt>실행 환경</dt><dd>Ollama · 로컬 전용</dd></div></dl></Panel><Panel className="panel-wide"><div className="panel-heading"><div><span className="eyebrow">접근 범위</span><h2>작업공간 경계</h2></div></div><dl className="detail-list"><div><dt>작업공간</dt><dd>{discovery?.workspaceRoot?.split(/[\\/]/).filter(Boolean).at(-1)??'—'}</dd></div><div><dt>선택한 프로젝트</dt><dd>{project?.projectId??'선택되지 않음'}</dd></div><div><dt>탐지된 프로젝트</dt><dd>{discovery?.projects.length??0}</dd></div><div><dt>프로젝트 묶음</dt><dd>{discovery?.containers.length??0}</dd></div></dl><p className="muted">절대 경로 입력이나 Workspace 밖 파일 접근 기능은 UI에 제공하지 않습니다.</p></Panel></div></>
}
