CREATE TABLE error_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    analysis_id UUID NOT NULL UNIQUE,
    project_id VARCHAR(512) NOT NULL,
    occurred_at TIMESTAMPTZ,
    recorded_at TIMESTAMPTZ NOT NULL,
    error_type TEXT,
    error_message TEXT,
    symptom TEXT NOT NULL,
    root_cause TEXT,
    solution TEXT,
    status VARCHAR(20) NOT NULL DEFAULT 'UNVERIFIED'
        CHECK (status IN ('UNVERIFIED', 'VERIFIED', 'RESOLVED')),
    related_files JSONB NOT NULL,
    related_commits JSONB NOT NULL,
    evidence_summary JSONB NOT NULL,
    created_by VARCHAR(64) NOT NULL,
    verification_note TEXT,
    verified_by VARCHAR(64),
    status_changed_at TIMESTAMPTZ,
    version BIGINT NOT NULL DEFAULT 0
);
CREATE INDEX error_history_project_recorded_idx ON error_history(project_id, recorded_at DESC, id DESC);
