CREATE TABLE error_history_verification (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    error_history_id BIGINT NOT NULL REFERENCES error_history(id) ON DELETE CASCADE,
    from_status VARCHAR(20) NOT NULL
        CHECK (from_status IN ('UNVERIFIED', 'VERIFIED', 'RESOLVED')),
    to_status VARCHAR(20) NOT NULL
        CHECK (to_status IN ('UNVERIFIED', 'VERIFIED', 'RESOLVED')),
    root_cause TEXT,
    solution TEXT,
    verification_note TEXT NOT NULL,
    actor VARCHAR(64) NOT NULL,
    changed_at TIMESTAMPTZ NOT NULL,
    previous_version BIGINT NOT NULL
);

CREATE INDEX error_history_verification_history_idx
    ON error_history_verification(error_history_id, changed_at, id);
CREATE INDEX error_history_status_recorded_idx
    ON error_history(project_id, status, recorded_at DESC, id DESC);
CREATE INDEX error_history_type_normalized_idx
    ON error_history(project_id, lower(btrim(error_type)), recorded_at DESC);
CREATE INDEX error_history_occurred_idx
    ON error_history(project_id, occurred_at);
CREATE INDEX error_history_related_files_gin_idx
    ON error_history USING GIN(related_files);
CREATE INDEX error_history_related_commits_gin_idx
    ON error_history USING GIN(related_commits);
