CREATE TABLE project_automation_config (
    project_id VARCHAR(512) PRIMARY KEY,
    enabled BOOLEAN NOT NULL DEFAULT FALSE,
    progress_summary_enabled BOOLEAN NOT NULL DEFAULT TRUE,
    activity_summary_enabled BOOLEAN NOT NULL DEFAULT TRUE,
    error_watch_enabled BOOLEAN NOT NULL DEFAULT TRUE,
    environment_watch_enabled BOOLEAN NOT NULL DEFAULT TRUE,
    interval_seconds INTEGER NOT NULL CHECK (interval_seconds >= 60),
    last_run_at TIMESTAMPTZ,
    next_run_at TIMESTAMPTZ,
    last_project_fingerprint VARCHAR(64),
    last_log_fingerprint VARCHAR(64),
    last_environment_fingerprint VARCHAR(64),
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    version BIGINT NOT NULL DEFAULT 0
);

CREATE INDEX project_automation_due_idx
    ON project_automation_config(enabled, next_run_at);

CREATE TABLE automation_run (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id VARCHAR(512) NOT NULL,
    trigger_type VARCHAR(20) NOT NULL,
    started_at TIMESTAMPTZ NOT NULL,
    finished_at TIMESTAMPTZ NOT NULL,
    status VARCHAR(30) NOT NULL,
    change_detected BOOLEAN NOT NULL,
    summary TEXT,
    error_message TEXT,
    result_details JSONB NOT NULL,
    duration_millis BIGINT NOT NULL
);

CREATE INDEX automation_run_project_started_idx
    ON automation_run(project_id, started_at DESC, id DESC);

CREATE TABLE detected_error_event (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id VARCHAR(512) NOT NULL,
    fingerprint VARCHAR(64) NOT NULL,
    detected_at TIMESTAMPTZ NOT NULL,
    log_timestamp VARCHAR(100),
    source_file VARCHAR(1024),
    line_number BIGINT,
    level VARCHAR(30),
    error_message TEXT NOT NULL,
    similar_lookup_status VARCHAR(30) NOT NULL,
    similar_count INTEGER NOT NULL DEFAULT 0,
    top_similar_history_id BIGINT,
    top_similarity DOUBLE PRECISION,
    UNIQUE(project_id, fingerprint)
);

CREATE INDEX detected_error_project_detected_idx
    ON detected_error_event(project_id, detected_at DESC, id DESC);

CREATE TABLE notification_candidate (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id VARCHAR(512) NOT NULL,
    automation_run_id BIGINT REFERENCES automation_run(id) ON DELETE SET NULL,
    notification_type VARCHAR(40) NOT NULL,
    fingerprint VARCHAR(64) NOT NULL,
    title VARCHAR(255) NOT NULL,
    summary TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL,
    acknowledged_at TIMESTAMPTZ,
    UNIQUE(project_id, notification_type, fingerprint)
);

CREATE INDEX notification_candidate_project_created_idx
    ON notification_candidate(project_id, created_at DESC, id DESC);
